### ISSUE TITLE
Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined"

### ISSUE THREAD

**Issue by nikongasparis** [hillaliy/homebridge-midea-air#11]
Hello. 
First of all thank you for this plugin. I'm using it on an Inventor AC and is working fine till now. 
I receive some "spam" messages in logs. Can you have a look please?

[5/23/2021, 1:32:17 PM] [homebridge-midea-air] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/23/2021, 1:32:17 PM] [homebridge-midea-air] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/Users/nikongasparis/.nvm/versions/node/v14.17.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/Users/nikongasparis/.nvm/versions/node/v14.17.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at TargetHeaterCoolerState.Characteristic.updateValue (/Users/nikongasparis/.nvm/versions/node/v14.17.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at HeaterCooler.Service.updateCharacteristic (/Users/nikongasparis/.nvm/versions/node/v14.17.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Timeout._onTimeout (/Users/nikongasparis/.nvm/versions/node/v14.17.0/lib/node_modules/homebridge-midea-air/lib/MideaAccessory.js:167:38)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)

**Comment by hillaliy** [comment]
Try to update to last version.
I'm using it too, no spam

**Comment by contactjorge** [comment]
I am also seeing this. I am a web developer but not the best node developer.

I managed to disable it but overwrote my settings. Not sure where it is being called. My assumption is that it is due to the hard coding of Celsius in one of the  response files or a discrepancy in setting the min max temp threshold (C vs F) for heat.

Unfortunately, I am also new to the HomeKit, Homebridge and midea api.  I was not doing an official git pull. Just tinkering.

I have 2020 and 2021 Midea U inverters. There are some slight differences. One issue I did manage to fix was HomeKit app resetting the device to Celsius. I still can’t figure out how to activate the other features in HomeKit but I know now where they are in the plug-in. I can open up issues/stories:

  *   Dry mode defaults to heat in HomeKit
  *   Would like to set Fahrenheit as preferred temperature
  *   Would like to remove heat all together
  *   Replace heat with dry in HomeKit app
  *   Turn off/on eco mode
  *   Get swing mode state
  *   Get led state
  *   Get sound state

I will see if I can find out how I disabled it in 4.1.3 and why it came back in 4.1.4

Jorge Lopez
Illinois

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hillaliy** [comment]
Hi!
1. If you use Fahrenheit that the problem. This plugin support for now only Celsius.
2. I can add Dry mode as a Service. you can't remove Heat and put Dry instead.

**Comment by nikongasparis** [comment]
Same issue with 1.1.4

**Comment by contactjorge** [comment]
A handler! I see. So that is what it’s called. I am still learning the ‘terminology.’

I was not sure what files were used to get/set homekit or homebridge and which were used to get/set the midea configuration.

I found this line in ACApplianceResponse.js

    get tempUnit() {
        // This needs a better name, dunno what it actually means
        // This gets the unit of measurement for the device.

       // return (this.data[0x09] & 0x80) > 0; // CELSIUS
        return this.data[23] > 0; // FAHRENHEIT
    }

Jorge

From: Yossi Hillali ***@***.***>
Reply-To: hillaliy/homebridge-midea-air ***@***.***>
Date: Monday, May 24, 2021 at 7:02 AM
To: hillaliy/homebridge-midea-air ***@***.***>
Cc: Jorge Lopez ***@***.***>, Comment ***@***.***>
Subject: Re: [hillaliy/homebridge-midea-air] Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (#11)


Hi!

  1.  If you use Fahrenheit that the problem. This plugin support for now only Celsius.
  2.  I can add Dry mode as a Service. you can't remove Heat and put Dry instead.

**Comment by hillaliy** [comment]
**I know those lines. I wrote them down**  

 get tempUnit() {
        // This needs a better name, dunno what it actually means
        // This gets the unit of measurement for the device.

       // return (this.data[0x09] & 0x80) > 0; // CELSIUS
        return this.data[23] > 0; // FAHRENHEIT
    }

**Comment by hillaliy** [comment]
This Plugin support now Fahrenheit
Version 1.2.0

**Comment by hillaliy** [comment]
There are models that are not yet supported by this plugin

**Comment by nikongasparis** [comment]
Not sure why it's closed. Network interface is the same(midea) and it uses the same api.

**Comment by hillaliy** [comment]
Check your dongle if it OSK103 this plugin don't support it.

**Comment by hillaliy** [comment]
Fix with version 1.2.1

**Comment by nikongasparis** [comment]
this is back on latest version
