### ISSUE TITLE
Stuck in Celsius on Homekit App.

### ISSUE THREAD

**Issue by mannyd209** [hillaliy/homebridge-midea-air#32]
After adding my mini split device, in the Homekit App it stays on Celsius and goes back to it when changed to Fahrenheit. Can you add a config setting to lock it to either C or F please? Thanks
![IMG_4817](https://user-images.githubusercontent.com/35792166/144665642-645552dd-f149-4f2b-ac72-5956a3f3a17a.jpg)

**Comment by hillaliy** [comment]
It's work perfect with my AC. OSK102.
Midea have a lot of providers and there is a little different between them.

**Comment by scaryfast8750** [comment]
I am having the same/similar issue.  

You can set the Unit = F in HomeKit under the accessory settings.  But the anytime you touch any setting in the homekit device it converts it back to Unit = C..sometimes on the unit, sometimes in HomeKit.  Its strangely inconsistent.

Example.
Change From Heat to Cool - Changes the Display to C on the Unit and the App
Turn the unit off or on - Changes the Display to C on the Unit and the App.

The NetHomeApp plus must be opened and change the units back to F to correct it.  Not matter what, the plugin Always goes back to C.

As a side note, it seems like this plugin doesn't poll for active configuration....maybe it just pushes settings because it will frequently be out of sync with what is actually happening from the Unit/NethomePlus.  This is not all the time, but there are small things I have seen with this like Fan Speed, F/C, Temp Range.

**Comment by hillaliy** [comment]
The Default unit is Celsius. this is just to control the temperature unit of the AC's display. The target temperature setter always expects a celsius temperature (resolution of 0.5C), as does the midea API
